version: '3.8'

services:
  # ----------------- FRONTEND (NGINX) -----------------
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Mount built frontend (Vue dist)
      - /usr/local/test/frontend/dist:/usr/share/nginx/html:ro
      # Custom nginx configuration
      - /usr/local/test/deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "hostserver:10.211.55.11"

