version: '3.8'

services:
  node-builder:
    image: node:22.20.0-alpine
    container_name: node_builder
    working_dir: /usr/src/app
    volumes:
      - /usr/local/test/frontend:/usr/src/app
      - ~/.npm-cache:/root/.npm
    command: >
      sh -c "
        npm ci || npm install &&
        npm run build
      "
    environment:
      - NODE_ENV=production
  # ----------------- FRONTEND (NGINX) -----------------
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Mount built frontend (Vue dist)
      - /usr/local/test/frontend/dist:/usr/share/nginx/html:ro
      # Custom nginx configuration
      - /usr/local/test/deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "hostserver:10.211.55.11"
    depends_on:
      - backend

  # ----------------- BACKEND (FASTAPI / UVICORN) -----------------
  backend:
    image: python:3.13.9
    container_name: churn_api
    restart: always
    working_dir: /usr/src/app
    volumes:
      # Mount the entire backend/app folder directly as working_dir
      - /usr/local/test/backend/app:/usr/src/app
      - /usr/local/test/backend/requirements.txt:/usr/src/app/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt &&
               python -m uvicorn churn_api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

